apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dotnet-app
  labels:
    app: my-dotnet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-dotnet-app
  template:
    metadata:
      labels:
        app: my-dotnet-app
    spec:
      containers:
      - name: my-dotnet-app
        image: codeyaazhnila/repo1:${GITHUB_SHA}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-dotnet-app
