name: Assign AKS Roles
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Assign AKS User Role
      run: |
        az role assignment create --assignee 0dfa47eb-cb5f-4a19-8edc-192901b73c82 --role "Azure Kubernetes Service Cluster User Role" --scope /subscriptions/f4ffefe1-d689-4059-969c-ccc73e2a11d4/resourcegroups/AKS1/providers/Microsoft.ContainerService/managedClusters/Cluster1

    - name: Enable Local Accounts
      run: |
        az aks update --resource-group AKS1 --name Cluster1 --enable-local-accounts

    - name: Assign Contributor Role
      run: |
        az role assignment create --assignee 0dfa47eb-cb5f-4a19-8edc-192901b73c82 --role "Contributor" --scope /subscriptions/f4ffefe1-d689-4059-969c-ccc73e2a11d4
