# This workflow will build a .NET project and deploy to AKS

name: Dotnet CICD

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output build_output
    - name: Test
      run: dotnet test --no-build --verbosity normal 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codeyaazhnila/repo1:${{ github.sha }} # docker registry name
    - name: Log in to Docker Hub using PAT
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push codeyaazhnila/repo1:${{ github.sha }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: artifact
        path: build_output/
    
    # AKS deployment steps
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install kubelogin
      run: |
        sudo apt-get update
        sudo apt-get install unzip -y
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.16/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/bin/linux_amd64/kubelogin
        sudo ln -s /usr/local/bin/bin/linux_amd64/kubelogin /usr/local/bin/kubelogin

    - name: Get AKS credentials
      run: |
          az aks get-credentials --name aks1 --overwrite-existing --resource-group AKS
          kubelogin convert-kubeconfig --login azurecli
    - name: Substitute GITHUB_SHA in deployment manifest
      run: sed -i 's/\${GITHUB_SHA}/'${{ github.sha }}'/g' kubernetes_deployment.yaml

    - name: Deploy to AKS
      run: kubectl apply -f kubernetes_deployment.yaml
